export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'terminal',
        'chat',
        'flow',
        'agents',
        'providers',
        'quota',
        'workspace',
        'settings',
        'web',
        'go',
        'infra',
        'security',
        'ui',
        'deps',
        'release',
      ],
    ],
    'subject-case': [0],
  },
};
