// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrapInfo() {
  return window['go']['desktop']['App']['GetBootstrapInfo']();
}

export function GetCapabilities() {
  return window['go']['desktop']['App']['GetCapabilities']();
}

export function GetSystemTheme() {
  return window['go']['desktop']['App']['GetSystemTheme']();
}

export function OpenExternal(arg1) {
  return window['go']['desktop']['App']['OpenExternal'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['desktop']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['desktop']['App']['SelectFile'](arg1);
}

export function ShowNotification(arg1) {
  return window['go']['desktop']['App']['ShowNotification'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['desktop']['App']['Shutdown'](arg1);
}
