// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {context} from '../models';

export function GetBootstrapInfo():Promise<desktop.BootstrapInfo>;

export function GetCapabilities():Promise<desktop.Capabilities>;

export function GetSystemTheme():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:desktop.FilePickerOptions):Promise<string>;

export function ShowNotification(arg1:desktop.NotificationOptions):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
