import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Save, SlidersHorizontal } from 'lucide-react';
import { Badge, Button, Card, EmptyState, Input, Select, Spinner } from '../../design-system';
import { nexus } from '../../nexus/api';
import type { Agent, AgentConfig, ConfigImpact } from '../../types';
const providers = ['', 'codex', 'claude', 'gemini', 'opencode', 'agy', 'cursor'].map((value) => ({ value, label: value || 'Automatic' }));
export const AgentConfigurationSurface: React.FC<{ agent?: Agent; onApplied?: () => void }> = ({ agent, onApplied }) => {
  const [config, setConfig] = useState<AgentConfig>({ provider: '', profile: 'default' }); const [impact, setImpact] = useState<ConfigImpact | null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(() => { if (!agent) { setLoading(false); return; } setLoading(true); nexus.getAgentConfig(agent.id).then((data)=>setConfig(data.config || {provider:'',profile:'default'})).catch((e)=>setError(e instanceof Error?e.message:String(e))).finally(()=>setLoading(false)); }, [agent]);
  const update = <K extends keyof AgentConfig>(key: K, value: AgentConfig[K]) => { setConfig((current)=>({...current,[key]:value})); setImpact(null); };
  const preview = async () => { if (!agent) return; setBusy(true); try { const result = await nexus.previewAgentConfig(agent.id,config); setImpact(result.impact); } catch(e){setError(e instanceof Error?e.message:String(e));} finally{setBusy(false);} };
  const apply = async () => { if (!agent) return; setBusy(true); try { const result=await nexus.applyAgentConfig(agent.id,config); setImpact(result.impact); await onApplied?.(); } catch(e){setError(e instanceof Error?e.message:String(e));} finally{setBusy(false);} };
  const modeTone = useMemo(()=>impact?.mode === 'NEW_SESSION' ? 'warning' : impact?.mode === 'RESTART_RUNTIME' ? 'info' : 'success',[impact]);
  if (loading) return <div className="nx-surface-center"><Spinner label="Loading Agent configuration…"/></div>;
  if (!agent) return <div className="nx-surface-center"><EmptyState icon={<SlidersHorizontal size={22}/>} title="Agent unavailable" hint="The selected Agent no longer exists."/></div>;
  return <div className="nx-surface-scroll"><div className="nx-page-header"><div><span className="nx-eyebrow">Agent configuration</span><h1>{agent.name}</h1><p>Configuration is versioned. Safe Apply previews continuity impact before the runtime changes.</p></div><Badge>{agent.continuity_status || 'continuity unknown'}</Badge></div>{error && <Card className="nx-inline-error"><AlertTriangle size={15}/>{error}</Card>}
    <div className="nx-config-grid"><Card className="nx-config-card"><h3>Provider & account</h3><Select label="Provider" value={config.provider || ''} onChange={(value)=>update('provider',value)} options={providers}/><label>Profile<Input value={config.profile || 'default'} onChange={(value)=>update('profile',value)} mono/></label><label>Model<Input value={config.model || ''} onChange={(value)=>update('model',value || undefined)} placeholder="Provider default" mono/></label></Card><Card className="nx-config-card"><h3>Execution</h3><label>Workspace override<Input value={config.workspace || ''} onChange={(value)=>update('workspace',value || undefined)} placeholder="Inherit Project path" mono/></label><Select label="Isolation" value={config.isolation || ''} onChange={(value)=>update('isolation',value || undefined)} options={[{value:'',label:'Project default'},{value:'project',label:'Project'},{value:'worktree',label:'Worktree'},{value:'none',label:'None'}]}/><Select label="Continuity" value={config.continuity_policy || ''} onChange={(value)=>update('continuity_policy',value || undefined)} options={[{value:'',label:'Automatic'},{value:'native',label:'Native resume only'},{value:'new_session',label:'Always new session'}]}/></Card><Card className="nx-config-card"><h3>Maestro & allocation</h3><Select label="Maestro" value={config.maestro_mode || ''} onChange={(value)=>update('maestro_mode',value || undefined)} options={[{value:'',label:'Project default'},{value:'OFF',label:'Off'},{value:'ASSIST',label:'Assist'},{value:'ORCHESTRATE',label:'Orchestrate'}]}/><Select label="Prefer provider" value={config.allocation?.prefer_provider || ''} onChange={(value)=>update('allocation',{...config.allocation,prefer_provider:value || undefined})} options={providers}/><label>Max concurrent<Input value={String(config.allocation?.max_concurrent || '')} onChange={(value)=>update('allocation',{...config.allocation,max_concurrent:value?Number(value):undefined})}/></label></Card></div>
    {impact && <Card className="nx-impact-card"><div>{modeTone === 'success' ? <CheckCircle2 size={16}/> : <AlertTriangle size={16}/>}<Badge tone={modeTone}>{impact.mode}</Badge></div><strong>{impact.requires_new_session ? 'New provider session required' : impact.requires_restart ? 'Runtime restart required' : 'Can be applied live'}</strong><p>{impact.changed_fields.length ? `Changed: ${impact.changed_fields.join(', ')}` : 'No configuration differences detected.'}</p>{impact.warnings?.map((warning)=><small key={warning}>{warning}</small>)}</Card>}
    <div className="nx-config-actions"><Button onClick={preview} disabled={busy}>Preview impact</Button><Button tone="brand" onClick={apply} disabled={busy}><Save size={14}/> Safe Apply</Button></div>
  </div>;
};
