import React, { useState } from 'react';
import { Bot, Play, Plus, RotateCcw, Settings2, Square, TerminalSquare } from 'lucide-react';
import { Badge, Button, Card, EmptyState, Input } from '../../design-system';
import { nexus } from '../../nexus/api';
import type { Agent, Project } from '../../types';

const tone = (status: string) => status === 'WORKING' ? 'success' : status === 'FAILED' || status === 'STALE' ? 'danger' : status === 'RECOVERABLE' || status === 'WAITING' || status === 'RATE_LIMITED' ? 'warning' : 'default';
export const AgentsSurface: React.FC<{ project: Project; agents: Agent[]; refresh: () => Promise<void>; onTerminal: (agent: Agent) => void; onConfigure: (agent: Agent) => void }> = ({ project, agents, refresh, onTerminal, onConfigure }) => {
  const [name, setName] = useState(''); const [busy, setBusy] = useState('');
  const create = async () => { if (!name.trim()) return; setBusy('create'); try { await nexus.createAgent(project.id, name.trim(), 'developer'); setName(''); await refresh(); } finally { setBusy(''); } };
  const action = async (agent: Agent, kind: 'start'|'stop'|'recover') => { setBusy(agent.id); try { if (kind === 'start') await nexus.startAgent(agent.id); else if (kind === 'stop') await nexus.stopAgent(agent.id); else await nexus.recoverAgent(agent.id); await refresh(); } finally { setBusy(''); } };
  return <div className="nx-surface-scroll"><div className="nx-page-header"><div><span className="nx-eyebrow">Persistent Agents</span><h1>Agent fleet</h1><p>Agents remain stable identities while runtimes and provider sessions evolve underneath them.</p></div><div className="nx-inline-create"><Input value={name} onChange={setName} onEnter={create} placeholder="Agent name…"/><Button tone="brand" disabled={!name.trim() || busy === 'create'} onClick={create}><Plus size={14}/> Create</Button></div></div>
    {agents.length === 0 ? <EmptyState icon={<Bot size={22}/>} title="No Agents in this Project" hint="Create a Backend, Frontend, Mobile, Reviewer or any role that should persist across runtimes."/> : <div className="nx-agent-grid">{agents.map((agent) => <Card key={agent.id} className="nx-agent-card"><div className="nx-agent-card__head"><span className="nx-agent-avatar nx-agent-avatar--large">{agent.name.slice(0,2).toUpperCase()}</span><div><strong>{agent.name}</strong><small>{agent.role || 'developer'} · {agent.id}</small></div><Badge tone={tone(agent.status)}>{agent.status}</Badge></div><div className="nx-agent-card__meta"><span>Continuity</span><strong>{agent.continuity_status || 'unknown'}</strong><span>Last start</span><strong>{agent.last_started_at || 'never'}</strong></div><div className="nx-agent-card__actions"><Button size="sm" onClick={() => onTerminal(agent)}><TerminalSquare size={13}/> Terminal</Button><Button size="sm" onClick={() => onConfigure(agent)}><Settings2 size={13}/> Configure</Button>{agent.status === 'WORKING' ? <Button size="sm" tone="danger" disabled={busy === agent.id} onClick={() => void action(agent,'stop')}><Square size={12}/> Stop</Button> : agent.status === 'RECOVERABLE' ? <Button size="sm" tone="warning" disabled={busy === agent.id} onClick={() => void action(agent,'recover')}><RotateCcw size={13}/> Recover</Button> : <Button size="sm" tone="brand" disabled={busy === agent.id} onClick={() => void action(agent,'start')}><Play size={13}/> Start</Button>}</div></Card>)}</div>}
  </div>;
};
