import React, { useEffect, useState } from 'react';
import { Activity, Check, Gauge, ShieldAlert } from 'lucide-react';
import { Badge, Button, EmptyState, Progress, Spinner } from '../design-system';
import { nexus } from './api';
import { translateStatus } from '../i18n';
import { useTranslation } from 'react-i18next';
interface ProviderAccount { id:string;provider:string;profile:string;display_name:string;authenticated:boolean;is_default:boolean;quota_remaining:number;quota_total:number;rate_limited:boolean;health:string; }
interface SchedulerDecision { selected:ProviderAccount|null;policy:string;reason:string;score:number;rejected:{account:ProviderAccount;reason:string}[];explain_path:string[]; }
interface Props { preferProvider?:string; onSelect:(provider:string,profile:string)=>void; }
const healthTone=(health:string)=>health==='healthy'?'success':health==='degraded'?'warning':health==='unhealthy'?'danger':'default';
export const ResourcePicker:React.FC<Props>=({preferProvider,onSelect})=>{const{t}=useTranslation();const[accounts,setAccounts]=useState<ProviderAccount[]>([]);const[decision,setDecision]=useState<SchedulerDecision|null>(null);const[loading,setLoading]=useState(true);const[selecting,setSelecting]=useState<string|null>(null);useEffect(()=>{let mounted=true;void nexus.listResources().then(async(data)=>{if(!mounted)return;setAccounts(data.accounts||[]);if(preferProvider){const result=await nexus.selectResource(preferProvider,'BALANCED');if(mounted)setDecision(result.decision);}}).catch(()=>undefined).finally(()=>mounted&&setLoading(false));return()=>{mounted=false};},[preferProvider]);const choose=async(account:ProviderAccount)=>{setSelecting(account.id);try{const result=await nexus.selectResource(account.provider,'BALANCED');setDecision(result.decision);onSelect(account.provider,account.profile);}finally{setSelecting(null);}};if(loading)return<Spinner label={t('resources.loading')}/>;if(accounts.length===0)return<EmptyState icon={<Gauge size={20}/>} title={t('resources.empty')} hint={t('resources.emptyHint')}/>;return<div className="nx-resource-picker"><div className="nx-resource-account-list">{accounts.map((account)=>{const selected=decision?.selected?.id===account.id;const quotaKnown=account.quota_total>0;const quotaPercent=quotaKnown?Math.round((account.quota_remaining/account.quota_total)*100):0;return<button key={account.id} type="button" className="nx-resource-account" data-selected={selected} onClick={()=>void choose(account)} disabled={!account.authenticated||selecting===account.id}><span className="nx-resource-account__icon">{account.rate_limited?<ShieldAlert size={17}/>:<Activity size={17}/>}</span><span className="nx-resource-account__main"><span className="nx-resource-account__title"><strong>{account.display_name||account.provider}</strong><Badge>{account.profile}</Badge><Badge tone={healthTone(account.health)}>{translateStatus(account.health)}</Badge>{account.is_default&&<Badge tone="brand">{t('common.default')}</Badge>}</span><span className="nx-resource-account__quota">{quotaKnown?<Progress value={quotaPercent} label={t("resources.remaining",{value:quotaPercent})}/>:<span>{t('resources.unknown')}</span>}</span></span><span>{account.rate_limited?<Badge tone="danger">{t('resources.rateLimited')}</Badge>:selected?<span className="nx-selected-check"><Check size={14}/> {t('common.selected')}</span>:<Button size="sm" tone="ghost">{t('common.use')}</Button>}</span></button>;})}</div>{decision&&<div className="nx-scheduler-explanation"><strong>{t('resources.decision')}</strong><p>{decision.reason||t('resources.balanced')}</p>{decision.explain_path?.length>0&&<ol>{decision.explain_path.map((item)=><li key={item}>{item}</li>)}</ol>}</div>}</div>;};
