import React from 'react';
import { Activity, Bot, FolderGit2, Gauge, ShieldCheck } from 'lucide-react';
import { Badge, Button, Card, EmptyState, Progress } from '../../design-system';
import type { Agent, Project } from '../../types';

const tone = (status: string) => status === 'WORKING' ? 'success' : status === 'FAILED' || status === 'STALE' ? 'danger' : status === 'RECOVERABLE' || status === 'WAITING' ? 'warning' : 'default';

export const ProjectOverviewSurface: React.FC<{ project: Project; agents: Agent[]; onOpenAgent: (agent: Agent) => void; onOpenWork: () => void; onOpenPlan: () => void }> = ({ project, agents, onOpenAgent, onOpenWork, onOpenPlan }) => {
  const working = agents.filter((agent) => agent.status === 'WORKING').length;
  const attention = agents.filter((agent) => ['FAILED','STALE','RECOVERABLE','RATE_LIMITED'].includes(agent.status)).length;
  return <div className="nx-surface-scroll"><div className="nx-page-header"><div><span className="nx-eyebrow">Project workspace</span><h1>{project.name}</h1><p>{project.canonical_path}</p></div><div className="nx-page-header__actions"><Button tone="brand" onClick={onOpenWork}>Start work</Button><Button onClick={onOpenPlan}>Open plan</Button></div></div>
    <div className="nx-metric-grid"><Card className="nx-metric-card"><span className="nx-metric-card__icon"><Bot size={18}/></span><div><strong>{agents.length}</strong><span>Persistent Agents</span></div></Card><Card className="nx-metric-card"><span className="nx-metric-card__icon"><Activity size={18}/></span><div><strong>{working}</strong><span>Working now</span></div></Card><Card className="nx-metric-card"><span className="nx-metric-card__icon"><Gauge size={18}/></span><div><strong>{project.resource_policy || 'BALANCED'}</strong><span>Resource policy</span></div></Card><Card className="nx-metric-card"><span className="nx-metric-card__icon"><ShieldCheck size={18}/></span><div><strong>{project.maestro_mode || 'ASSIST'}</strong><span>Maestro mode</span></div></Card></div>
    <div className="nx-overview-columns"><Card className="nx-overview-card"><div className="nx-section-title"><div><h2>Agent fleet</h2><p>Stable Agent identities attached to this Project.</p></div><Badge tone={attention > 0 ? 'warning' : 'success'}>{attention > 0 ? `${attention} need attention` : 'healthy'}</Badge></div>{agents.length === 0 ? <EmptyState icon={<Bot size={20}/>} title="No Agents yet" hint="Create an Agent to start a persistent AI development session."/> : <div className="nx-agent-mini-list">{agents.slice(0,8).map((agent) => <button className="nx-agent-mini" key={agent.id} onClick={() => onOpenAgent(agent)}><span className="nx-agent-avatar">{agent.name.slice(0,2).toUpperCase()}</span><span className="nx-agent-mini__copy"><strong>{agent.name}</strong><small>{agent.role || 'Development Agent'} · {agent.continuity_status || 'continuity pending'}</small></span><Badge tone={tone(agent.status)}>{agent.status}</Badge></button>)}</div>}</Card>
      <Card className="nx-overview-card"><div className="nx-section-title"><div><h2>Project readiness</h2><p>Operational context that remains attached to this Project.</p></div></div><div className="nx-readiness-list"><div><span><FolderGit2 size={14}/> Repository</span><strong>{project.default_branch || 'main'}</strong></div><div><span>Maestro</span><strong>{project.maestro_mode || 'ASSIST'}</strong></div><div><span>Isolation</span><strong>{project.default_isolation || 'project'}</strong></div><div><span>Active Agents</span><strong>{working}</strong></div></div><div className="nx-readiness-progress"><Progress value={Math.min(100, 40 + (agents.length ? 25 : 0) + (project.maestro_mode !== 'OFF' ? 20 : 0) + (project.resource_policy ? 15 : 0))} label="Workspace configuration readiness"/></div></Card></div>
  </div>;
};
