export interface ThemeDefinition {
  id: string;
  name: string;
  scheme: 'dark' | 'light' | 'high-contrast';
  accent: string;
  vars: Record<string, string>;
}

export const THEME_PRESETS: Record<string, ThemeDefinition> = {
  'nexus-dark': {
    id: 'nexus-dark',
    name: 'Nexus Dark',
    scheme: 'dark',
    accent: '#8b5cf6',
    vars: {
      '--nx-bg': '#080a0f',
      '--nx-bg-elevated': '#0c0f15',
      '--nx-surface': '#10131a',
      '--nx-surface-2': '#151922',
      '--nx-surface-3': '#1a1f2b',
      '--nx-border': '#202633',
      '--nx-border-strong': '#303849',
      '--nx-text': '#f1f3f7',
      '--nx-text-soft': '#d9dde6',
      '--nx-muted': '#8a93a5',
      '--nx-subtle': '#626c82',
      '--nx-accent': '#8b5cf6',
      '--nx-accent-hover': '#9f75ff',
      '--nx-accent-soft': 'rgba(139, 92, 246, 0.14)',
      '--nx-accent-text': '#bba5ff',
    },
  },
  'nexus-light': {
    id: 'nexus-light',
    name: 'Nexus Light',
    scheme: 'light',
    accent: '#7c3aed',
    vars: {
      '--nx-bg': '#f4f6fa',
      '--nx-bg-elevated': '#ffffff',
      '--nx-surface': '#ffffff',
      '--nx-surface-2': '#f0f3f8',
      '--nx-surface-3': '#e8edf4',
      '--nx-border': '#d7dde8',
      '--nx-border-strong': '#bcc5d5',
      '--nx-text': '#141821',
      '--nx-text-soft': '#2d3442',
      '--nx-muted': '#5e687b',
      '--nx-subtle': '#7a869a',
      '--nx-accent': '#7c3aed',
      '--nx-accent-hover': '#6d28d9',
      '--nx-accent-soft': 'rgba(124, 58, 237, 0.12)',
      '--nx-accent-text': '#6d28d9',
    },
  },
  'midnight': {
    id: 'midnight',
    name: 'Midnight',
    scheme: 'dark',
    accent: '#38bdf8',
    vars: {
      '--nx-bg': '#030712',
      '--nx-bg-elevated': '#0b0f19',
      '--nx-surface': '#111827',
      '--nx-surface-2': '#1f2937',
      '--nx-surface-3': '#374151',
      '--nx-border': '#1e293b',
      '--nx-border-strong': '#334155',
      '--nx-text': '#f8fafc',
      '--nx-text-soft': '#e2e8f0',
      '--nx-muted': '#94a3b8',
      '--nx-subtle': '#64748b',
      '--nx-accent': '#38bdf8',
      '--nx-accent-hover': '#0ea5e9',
      '--nx-accent-soft': 'rgba(56, 189, 248, 0.14)',
      '--nx-accent-text': '#7dd3fc',
    },
  },
  'nord': {
    id: 'nord',
    name: 'Nord',
    scheme: 'dark',
    accent: '#88c0d0',
    vars: {
      '--nx-bg': '#242933',
      '--nx-bg-elevated': '#2e3440',
      '--nx-surface': '#3b4252',
      '--nx-surface-2': '#434c5e',
      '--nx-surface-3': '#4c566a',
      '--nx-border': '#434c5e',
      '--nx-border-strong': '#4c566a',
      '--nx-text': '#eceff4',
      '--nx-text-soft': '#e5e9f0',
      '--nx-muted': '#d8dee9',
      '--nx-subtle': '#9aa5b8',
      '--nx-accent': '#88c0d0',
      '--nx-accent-hover': '#81a1c1',
      '--nx-accent-soft': 'rgba(136, 192, 208, 0.16)',
      '--nx-accent-text': '#8fbcbb',
    },
  },
  'dracula': {
    id: 'dracula',
    name: 'Dracula',
    scheme: 'dark',
    accent: '#bd93f9',
    vars: {
      '--nx-bg': '#1e1f29',
      '--nx-bg-elevated': '#282a36',
      '--nx-surface': '#343746',
      '--nx-surface-2': '#44475a',
      '--nx-surface-3': '#6272a4',
      '--nx-border': '#44475a',
      '--nx-border-strong': '#6272a4',
      '--nx-text': '#f8f8f2',
      '--nx-text-soft': '#e2e2dc',
      '--nx-muted': '#bfbfba',
      '--nx-subtle': '#6272a4',
      '--nx-accent': '#bd93f9',
      '--nx-accent-hover': '#ff79c6',
      '--nx-accent-soft': 'rgba(189, 147, 249, 0.16)',
      '--nx-accent-text': '#ff79c6',
    },
  },
  'monokai': {
    id: 'monokai',
    name: 'Monokai',
    scheme: 'dark',
    accent: '#a6e22e',
    vars: {
      '--nx-bg': '#1e1f1c',
      '--nx-bg-elevated': '#272822',
      '--nx-surface': '#383830',
      '--nx-surface-2': '#49483e',
      '--nx-surface-3': '#75715e',
      '--nx-border': '#49483e',
      '--nx-border-strong': '#75715e',
      '--nx-text': '#f8f8f2',
      '--nx-text-soft': '#e6db74',
      '--nx-muted': '#cfcfc2',
      '--nx-subtle': '#75715e',
      '--nx-accent': '#a6e22e',
      '--nx-accent-hover': '#f92672',
      '--nx-accent-soft': 'rgba(166, 226, 46, 0.16)',
      '--nx-accent-text': '#fd971f',
    },
  },
  'solarized-dark': {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    scheme: 'dark',
    accent: '#268bd2',
    vars: {
      '--nx-bg': '#00212b',
      '--nx-bg-elevated': '#002b36',
      '--nx-surface': '#073642',
      '--nx-surface-2': '#094252',
      '--nx-surface-3': '#0b5063',
      '--nx-border': '#073642',
      '--nx-border-strong': '#586e75',
      '--nx-text': '#93a1a1',
      '--nx-text-soft': '#eee8d5',
      '--nx-muted': '#839496',
      '--nx-subtle': '#586e75',
      '--nx-accent': '#268bd2',
      '--nx-accent-hover': '#2aa198',
      '--nx-accent-soft': 'rgba(38, 139, 210, 0.16)',
      '--nx-accent-text': '#2aa198',
    },
  },
  'solarized-light': {
    id: 'solarized-light',
    name: 'Solarized Light',
    scheme: 'light',
    accent: '#268bd2',
    vars: {
      '--nx-bg': '#fdf6e3',
      '--nx-bg-elevated': '#eee8d5',
      '--nx-surface': '#f5efdc',
      '--nx-surface-2': '#e6dfcb',
      '--nx-surface-3': '#d3ccb8',
      '--nx-border': '#d3ccb8',
      '--nx-border-strong': '#93a1a1',
      '--nx-text': '#586e75',
      '--nx-text-soft': '#073642',
      '--nx-muted': '#657b83',
      '--nx-subtle': '#839496',
      '--nx-accent': '#268bd2',
      '--nx-accent-hover': '#2aa198',
      '--nx-accent-soft': 'rgba(38, 139, 210, 0.14)',
      '--nx-accent-text': '#268bd2',
    },
  },
  'high-contrast-dark': {
    id: 'high-contrast-dark',
    name: 'High Contrast Dark',
    scheme: 'high-contrast',
    accent: '#ffff00',
    vars: {
      '--nx-bg': '#000000',
      '--nx-bg-elevated': '#000000',
      '--nx-surface': '#050505',
      '--nx-surface-2': '#0b0b0b',
      '--nx-surface-3': '#111111',
      '--nx-border': '#8f8f8f',
      '--nx-border-strong': '#ffffff',
      '--nx-text': '#ffffff',
      '--nx-text-soft': '#ffffff',
      '--nx-muted': '#e2e2e2',
      '--nx-subtle': '#c7c7c7',
      '--nx-accent': '#ffff00',
      '--nx-accent-hover': '#fff866',
      '--nx-accent-soft': 'rgba(255, 255, 0, 0.2)',
      '--nx-accent-text': '#ffff00',
    },
  },
  'high-contrast-light': {
    id: 'high-contrast-light',
    name: 'High Contrast Light',
    scheme: 'light',
    accent: '#0000ee',
    vars: {
      '--nx-bg': '#ffffff',
      '--nx-bg-elevated': '#ffffff',
      '--nx-surface': '#ffffff',
      '--nx-surface-2': '#f0f0f0',
      '--nx-surface-3': '#e0e0e0',
      '--nx-border': '#000000',
      '--nx-border-strong': '#000000',
      '--nx-text': '#000000',
      '--nx-text-soft': '#000000',
      '--nx-muted': '#1a1a1a',
      '--nx-subtle': '#333333',
      '--nx-accent': '#0000ee',
      '--nx-accent-hover': '#0000aa',
      '--nx-accent-soft': 'rgba(0, 0, 238, 0.15)',
      '--nx-accent-text': '#0000ee',
    },
  },
};
